// ─── Subject ──────────────────────────────────────────────────────────────────
import type { Inventory } from './inventory'
import type { ClassId } from './character'

export type Subject = 'listening' | 'speaking' | 'reading' | 'writing'

// ─── Auth ─────────────────────────────────────────────────────────────────────
// POST /api/auth/login
export interface LoginRequest {
  username: string
  password: string
}

export interface LoginResponse {
  userId: string
  name: string
  // Backend may include additional fields like token, refreshToken, etc.
}

// ─── Question Set (list view) ─────────────────────────────────────────────────
// Returned by GET /api/question-sets?subject=...
export interface QuestionSet {
  id: string
  title: string
  type: string                          // e.g. "Short Conversations", "Multiple Choice"
  subject: Subject
  difficulty: 'Easy' | 'Medium' | 'Hard'
  duration: string                      // e.g. "3:45"
  questionCount: number
  status: 'completed' | 'incomplete' | 'wrong'
  score?: number                        // last attempt score, if attempted
  audioUrl?: string                     // listening only
  transcript?: string                   // listening only
  context?: string                      // speaking/oral/writing: passage or prompt
}

// ─── Question ─────────────────────────────────────────────────────────────────
// Returned by GET /api/questions?setId=...
// NOTE: correct answer is NOT included — backend validates on submission
export interface Question {
  id: string
  no: number
  text: string
  options: string[]                     // ["A. Some text", "B. Other text", ...]
}

// ─── Submit ───────────────────────────────────────────────────────────────────
// POST /api/submit
export interface SubmitPayload {
  setId: string
  subject: Subject
  answers: Record<string, string>       // { questionId: 'A' | 'B' | 'C' | 'D' }
}

// ─── Submit Response ──────────────────────────────────────────────────────────
export interface QuestionResult {
  questionId: string
  isCorrect: boolean
  correctAnswer: string                 // 'A' | 'B' | 'C' | 'D'
  analysis?: AIAnalysis | null          // when backend generates AI tutor content
  goldEarned?: number                  // optional per-question gold
  bossDamage?: number                  // optional per-question damage to boss
  charDamage?: number                  // optional per-question damage to player character
}

export interface SubmitResponse {
  score: number
  total: number
  xpEarned: number
  results: QuestionResult[]
  // If backend wants to be fully authoritative, it can return the updated inventory snapshot here.
  updatedInventory?: Inventory
}

// ─── Live boss teaser (Dashboard cover) ────────────────────────────────────
export interface LiveBossTeaser {
  bossType: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  bossName: string
  bossHp: number 
  bossMaxHp: number
  bossColor: string            // e.g. '#dc2626'
  goldReward?: number         // optional reward shown on teaser
  battleSubject: Subject      // which quiz route to start
}

// ─── Dashboard: weekly streak ────────────────────────────────────────────
export interface WeeklyStreak {
  // length must be 7, ordered Mon..Sun
  streakDays: boolean[]
  streakCount: number
}

// ─── Dashboard: wrong questions review ───────────────────────────────────
export interface WrongQuestionsReviewEntry {
  subject: Subject
  wrongCount: number
}

export interface WrongQuestionsReview {
  // aggregate by subject (4 entries typically)
  entries: WrongQuestionsReviewEntry[]
}

// AI tutor analysis content generated by backend (or any other server-side source).
export interface AIAnalysis {
  why: string         // Why the correct answer is correct
  grammarTip: string  // Grammar or structure tip
  vocabNote: string   // Vocabulary or usage note
}

// ─── Auth: Register ─────────────────────────────────────────────────────────
export interface RegisterRequest {
  username: string
  password: string
  name: string
}

export interface RegisterResponse {
  userId: string
  name: string
  username: string
}

// ─── Character ──────────────────────────────────────────────────────────────
export interface CreateCharacterRequest {
  classId: ClassId
  name: string
}

export interface CharacterResponse {
  userId: string
  classId: ClassId
  name: string
  xp: number
  level: number
}

// ─── Multiplayer Room ────────────────────────────────────────────────────────
export interface CreateRoomResponse {
  roomCode: string
  hostId: string
  subject: Subject
  difficulty: 'Easy' | 'Medium' | 'Hard'
}

export interface JoinRoomResponse {
  roomCode: string
  hostId: string
  players: PlayerInfo[]
  subject: Subject
  difficulty: 'Easy' | 'Medium' | 'Hard'
}

export interface PlayerInfo {
  id: string
  name: string
  classId: ClassId
}

// ─── Dashboard: Stats ────────────────────────────────────────────────────────
export interface DashboardStats {
  totalXp: number
  level: number
  totalGold: number
  totalQuestionsAnswered: number
  correctRate: number
  longestStreak: number
  subjectStats: SubjectStat[]
}

export interface SubjectStat {
  subject: Subject
  difficulty?: string
  attempted?: number
  correct?: number
  accuracy?: number   // used by /wrong-answer-analysis
  totalAnswered?: number
  correctRate?: number
  xpEarned?: number
  badge?: string
}

// ─── Dashboard: Wrong Answer Analysis (AI-powered) ─────────────────────────
export interface WrongSubjectEntry {
  subject: Subject
  accuracy: number
}

export interface WrongAnswerAnalysis {
  summary: SubjectStat[]
  tips: string
  weakestSubject: Subject | null
  weakSubjects: WrongSubjectEntry[]
}
